#!/usr/bin/env bash

SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
ROOT_DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

THIRDPARTY=${ROOT_DIR}/thirdparty

EDITOR=emacs

append_to_variable() {
    set +o pipefail
    set -x

    local variable env_variable to_append delimiter
    variable="$1"
    env_variable="$""${variable}"
    echo "$env_variable"
    to_append="$2"
    delimiter="${3:-:}"

    echo "${env_variable}" | tr "${delimiter}" "\n" | grep "${to_append}" > /dev/null || export "${variable}"="${env_variable}${delimiter}${to_append}"

    set +x
    set -o pipefail
}

source ${ROOT_DIR}/bash_config.bash
source ${THIRDPARTY}/fzf/shell/key-bindings.bash
source ${THIRDPARTY}/fzf/shell/completion.bash
source ${THIRDPARTY}/fzf-git/fzf-git.sh
source ${ROOT_DIR}/fzf_config.bash
source ${ROOT_DIR}/tmux_start.bash
